cover:
  - platform: time_based
    name: 'Cover 01'
    id: cover_01
    open_action:
      - switch.turn_off: cover_close_01_out02
      - switch.turn_on: cover_open_01_out01
    open_duration: 10s
    close_action:
      - switch.turn_off: cover_open_01_out01
      - switch.turn_on: cover_close_01_out02
    close_duration: 10s
    stop_action:
      - switch.turn_off: cover_open_01_out01
      - switch.turn_off: cover_close_01_out02

  - platform: time_based
    name: 'Cover 02'
    id: cover_02
    open_action:
      - switch.turn_off: cover_close_02_out04
      - switch.turn_on: cover_open_02_out03
    open_duration: 10s
    close_action:
      - switch.turn_off: cover_open_02_out03
      - switch.turn_on: cover_close_02_out04
    close_duration: 10s
    stop_action:
      - switch.turn_off: cover_open_02_out03
      - switch.turn_off: cover_close_02_out04

  - platform: time_based
    name: 'Cover 03'
    id: cover_03
    open_action:
      - switch.turn_off: cover_close_03_out06
      - switch.turn_on: cover_open_03_out05
    open_duration: 10s
    close_action:
      - switch.turn_off: cover_open_03_out05
      - switch.turn_on: cover_close_03_out06
    close_duration: 10s
    stop_action:
      - switch.turn_off: cover_open_03_out05
      - switch.turn_off: cover_close_03_out06

light:
  - platform: binary
    name: 'Light 07'
    output: out_07
    id: light_07
  - platform: binary
    name: 'Light 08'
    output: out_08
    id: light_08
  - platform: binary
    name: 'Light 09'
    output: out_09
    id: light_09
  - platform: binary
    name: 'Light 10'
    output: out_10
    id: light_10
  - platform: binary
    name: 'Light 11'
    output: out_11
    id: light_11
  - platform: binary
    name: 'Light 12'
    output: out_12
    id: light_12
  - platform: binary
    name: 'Light 13'
    output: out_13
    id: light_13
  - platform: binary
    name: 'Light 14'
    output: out_14
    id: light_14
  - platform: binary
    name: 'Light 15'
    output: out_15
    id: light_15
  - platform: binary
    name: 'Light 16'
    output: out_16
    id: light_16
  - platform: binary
    name: 'Light 17'
    output: out_17
    id: light_17
  - platform: binary
    name: 'Light 18'
    output: out_18
    id: light_18
  - platform: binary
    name: 'Light 19'
    output: out_19
    id: light_19
  - platform: binary
    name: 'Light 20'
    output: out_20
    id: light_20
  - platform: binary
    name: 'Light 21'
    output: out_21
    id: light_21
  - platform: binary
    name: 'Light 22'
    output: out_22
    id: light_22
  - platform: binary
    name: 'Light 23'
    output: out_23
    id: light_23
  
switch:
  - platform: output
    name: 'Switch 24'
    output: out_24
    id: switch_24
  - platform: output
    name: 'Switch 25'
    output: out_25
    id: switch_25
  - platform: output
    name: 'Switch 26'
    output: out_26
    id: switch_26
  - platform: output
    name: 'Switch 27'
    output: out_27
    id: switch_27
  - platform: output
    name: 'Switch 28'
    output: out_28
    id: switch_28
  - platform: output
    name: 'Switch 29'
    output: out_29
    id: switch_29
  - platform: output
    name: 'Switch 30'
    output: out_30
    id: switch_30
  - platform: output
    name: 'Switch 31'
    output: out_31
    id: switch_31
  - platform: output
    name: 'Switch 32'
    output: out_32
    id: switch_32

binary_sensor:

  - platform: gpio
    name: 'IN_01'
    id: in_01
    pin:
      pcf8574: pcf_inputs_1to14
      number: 0
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - cover.open: cover_01
    on_release:
      then:
        - cover.stop: cover_01

  - platform: gpio
    name: 'IN_02'
    id: in_02
    pin:
      pcf8574: pcf_inputs_1to14
      number: 1
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - cover.close: cover_01
    on_release:
      then:
        - cover.stop: cover_01

  - platform: gpio
    name: 'IN_03'
    id: in_03
    pin:
      pcf8574: pcf_inputs_1to14
      number: 2
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - cover.open: cover_02
    on_release:
      then:
        - cover.stop: cover_02

  - platform: gpio
    name: 'IN_04'
    id: in_04
    pin:
      pcf8574: pcf_inputs_1to14
      number: 3
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - cover.close: cover_02
    on_release:
      then:
        - cover.stop: cover_02

  - platform: gpio
    name: 'IN_05'
    id: in_05
    pin:
      pcf8574: pcf_inputs_1to14
      number: 4
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - cover.open: cover_03
    on_release:
      then:
        - cover.stop: cover_03

  - platform: gpio
    name: 'IN_06'
    id: in_06
    pin:
      pcf8574: pcf_inputs_1to14
      number: 5
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - cover.close: cover_03
    on_release:
      then:
        - cover.stop: cover_03

  - platform: gpio
    name: 'IN_07'
    id: in_07
    pin:
      pcf8574: pcf_inputs_1to14
      number: 6
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_07

  - platform: gpio
    name: 'IN_08'
    id: in_08
    pin:
      pcf8574: pcf_inputs_1to14
      number: 8
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_08

  - platform: gpio
    name: 'IN_09'
    id: in_09
    pin:
      pcf8574: pcf_inputs_1to14
      number: 9
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_09

  - platform: gpio
    name: 'IN_10'
    id: in_10
    pin:
      pcf8574: pcf_inputs_1to14
      number: 10
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_10

  - platform: gpio
    name: 'IN_11'
    id: in_11
    pin:
      pcf8574: pcf_inputs_1to14
      number: 11
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_11

  - platform: gpio
    name: 'IN_12'
    id: in_12
    pin:
      pcf8574: pcf_inputs_1to14
      number: 12
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_12

  - platform: gpio
    name: 'IN_13'
    id: in_13
    pin:
      pcf8574: pcf_inputs_1to14
      number: 13
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_13

  - platform: gpio
    name: 'IN_14'
    id: in_14
    pin:
      pcf8574: pcf_inputs_1to14
      number: 14
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_14

  - platform: gpio
    name: 'IN_15'
    id: in_15
    pin:
      pcf8574: pcf_inputs_15to28
      number: 6
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_15

  - platform: gpio
    name: 'IN_16'
    id: in_16
    pin:
      pcf8574: pcf_inputs_15to28
      number: 5
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_16

  - platform: gpio
    name: 'IN_17'
    id: in_17
    pin:
      pcf8574: pcf_inputs_15to28
      number: 4
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_17

  - platform: gpio
    name: 'IN_18'
    id: in_18
    pin:
      pcf8574: pcf_inputs_15to28
      number: 3
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_18

  - platform: gpio
    name: 'IN_19'
    id: in_19
    pin:
      pcf8574: pcf_inputs_15to28
      number: 2
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_19

  - platform: gpio
    name: 'IN_20'
    id: in_20
    pin:
      pcf8574: pcf_inputs_15to28
      number: 1
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_20

  - platform: gpio
    name: 'IN_21'
    id: in_21
    pin:
      pcf8574: pcf_inputs_15to28
      number: 0
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_21

  - platform: gpio
    name: 'IN_22'
    id: in_22
    pin:
      pcf8574: pcf_inputs_15to28
      number: 8
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_22

  - platform: gpio
    name: 'IN_23'
    id: in_23
    pin:
      pcf8574: pcf_inputs_15to28
      number: 9
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_23

  - platform: gpio
    name: 'IN_24'
    id: in_24
    pin:
      pcf8574: pcf_inputs_15to28
      number: 10
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: switch_24

  - platform: gpio
    name: 'IN_25'
    id: in_25
    pin:
      pcf8574: pcf_inputs_15to28
      number: 11
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: switch_25

  - platform: gpio
    name: 'IN_26'
    id: in_26
    pin:
      pcf8574: pcf_inputs_15to28
      number: 12
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: switch_26

  - platform: gpio
    name: 'IN_27'
    id: in_27
    pin:
      pcf8574: pcf_inputs_15to28
      number: 13
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: switch_27

  - platform: gpio
    name: 'IN_28'
    id: in_28
    pin:
      pcf8574: pcf_inputs_15to28
      number: 14
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: switch_28

  - platform: gpio
    name: 'IN_29'
    id: in_29
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 0
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: switch_29

  - platform: gpio
    name: 'IN_30'
    id: in_30
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 1
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: switch_30

  - platform: gpio
    name: 'IN_31'
    id: in_31
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 2
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: switch_31

  - platform: gpio
    name: 'IN_32'
    id: in_32
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 3
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: switch_32

  - platform: gpio
    name: 'IN_33'
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 4
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: 'IN_34'
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 5
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: 'IN_35'
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 6
      mode:
        input: true
      inverted: true