sensor:
  - platform: ina219
    address: 0x40
    shunt_resistance: 0.005 ohm
    bus_voltage:
      name: 'VDDL Supply'
      entity_category: diagnostic
    power:
      name: 'VDDL Power'
      entity_category: diagnostic
    current:
      name: 'VDDL Current'
      entity_category: diagnostic
    shunt_voltage:
      name: 'VDDL Shunt Voltage'
      entity_category: diagnostic
    max_voltage: 32V
    max_current: 10A
    update_interval: 5s
  - platform: ina219
    address: 0x41
    shunt_resistance: 0.005 ohm
    bus_voltage:
      name: 'VDDR Supply'
      entity_category: diagnostic
    power:
      name: 'VDDR Power'
      entity_category: diagnostic
    current:
      name: 'VDDR Current'
      entity_category: diagnostic
    shunt_voltage:
      name: 'VDDR Shunt Voltage'
      entity_category: diagnostic
    max_voltage: 32V
    max_current: 10A
    update_interval: 5s
